# Generated by Django 5.2 on 2025-05-02 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_reader_card_number_alter_reader_email_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reader',
        ),
    ]
