# Generated by Django 5.2 on 2025-05-02 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reader',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
