# Generated by Django 5.2 on 2025-05-09 14:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_reader_is_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='reader',
            name='reader_number',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=12, unique=True),
        ),
    ]
