# Generated by Django 5.2 on 2025-05-04 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_author_book_authors'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exampler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventory_number', models.IntegerField(unique=True)),
                ('condition', models.CharField(max_length=100)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exemplars', to='books.book')),
            ],
        ),
    ]
