# Generated by Django 5.2 on 2025-05-09 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_exampler'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exampler',
            name='inventory_number',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
