# Generated by Django 5.2 on 2025-05-09 09:55

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_genre_book_genres'),
        ('main', '0005_reader_is_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Issuance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issuance_date', models.DateField(default=django.utils.timezone.now)),
                ('return_date', models.DateField(default=datetime.datetime(2025, 5, 23, 9, 55, 15, 832001, tzinfo=datetime.timezone.utc))),
                ('rating', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
                ('exampler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issuances', to='books.exampler')),
                ('reader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issuances', to='main.reader')),
            ],
            options={
                'unique_together': {('reader', 'exampler')},
            },
        ),
    ]
