# Generated by Django 5.2 on 2025-05-09 14:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_issuance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuance',
            name='return_date',
            field=models.DateField(default=datetime.datetime(2025, 5, 23, 14, 49, 36, 198026, tzinfo=datetime.timezone.utc)),
        ),
    ]
