# Generated by Django 5.2 on 2025-05-09 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_alter_issuance_return_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuance',
            name='status',
            field=models.CharField(choices=[('active', 'Активный'), ('overdue', 'Просрочено'), ('returned', 'Вернута')], default='active', max_length=10),
        ),
        migrations.AlterField(
            model_name='issuance',
            name='return_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
