# Generated by Django 5.2 on 2025-05-09 16:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_issuance_status_alter_issuance_return_date'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='issuance',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='issuance',
            name='issuance_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='issuance',
            name='return_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
